### ISSUE TITLE
Check FTX exchange get_target_price

### ISSUE THREAD

**Issue by arnaudj** [atkinson/wagmi#13]
Something to check computations of https://github.com/atkinson/wagmi/blob/master/execution/exchanges/ftx.py#L68

**Comment by arnaudj** [comment]
Work in progress in https://github.com/arnaudj/wagmi/commits/dev/midpoint
Feedback welcome

**Comment by CharlesFr** [comment]
Nice, where were you thinking of placing the logic to check order status? I presume we'll need a loop that checks until all orders are filled and update the price?

Currently, Orders are created one by one, so in my branch I've added [a function ](https://github.com/atkinson/wagmi/blob/c1cf83266e648836e8e679bde1b8c90491dd1e79/weights/runner.py#L64) to process them together as a QuerySet.

**Comment by arnaudj** [comment]
Good question @CharlesFr

Can we discuss this in #15 or another issue?

afaik, we have this flow: TargetPositionManager -> positions planning (in OrderManager::create_order) -> placing orders on exchange (FTXExchange). So possibly in the execution module, regularly called (some kind of tick())

**Comment by arnaudj** [comment]
PR #14 merged
