### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by atkinson** [atkinson/wagmi#6]
something to run the build and test when someone submits a PR.

**Comment by arnaudj** [comment]
Will give it a try

**Comment by arnaudj** [comment]
My current plan for the next steps

For this issue: add a github action that runs docker-compose, followed by a simple health check (eg, ensure `localhost:8080/wagmi` is up and running). This would be a smoke test to validate django starts ok.

For unit tests (#5), we should be able to run tests from within the container. Eg with this pattern: https://docs.docker.com/language/java/run-tests/

(open to suggestions)

**Comment by atkinson** [comment]
That sounds good, Arnaud - whatever is simplest and has the least code.
